version: '3.8'

services:
  # Langflow Backend Service
  langflow-backend:
    image: langflowai/langflow:latest
    container_name: axie-studio-backend
    restart: unless-stopped
    environment:
      - LANGFLOW_DATABASE_URL=sqlite:///app/langflow.db
      - LANGFLOW_AUTO_LOGIN=false
      - LANGFLOW_SUPERUSER=${AXIE_STUDIO_SUPERUSER:-admin}
      - LANGFLOW_SUPERUSER_PASSWORD=${AXIE_STUDIO_SUPERUSER_PASSWORD:-admin123}
      - LANGFLOW_SECRET_KEY=${LANGFLOW_SECRET_KEY:-your-secret-key-here}
      - LANGFLOW_LOG_LEVEL=INFO
      - LANGFLOW_HOST=0.0.0.0
      - LANGFLOW_PORT=7860
    volumes:
      - langflow_data:/app/langflow
      - ./logs:/app/logs
    ports:
      - "7860:7860"
    networks:
      - axie-studio-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Axie Studio Frontend Service
  axie-studio-frontend:
    build:
      context: ./axie-studio-frontend
      dockerfile: Dockerfile.axie-studio
    container_name: axie-studio-frontend
    restart: unless-stopped
    environment:
      - LANGFLOW_BACKEND_URL=http://langflow-backend:7860
      - AXIE_STUDIO_SUPERUSER=${AXIE_STUDIO_SUPERUSER:-admin}
      - AXIE_STUDIO_SUPERUSER_PASSWORD=${AXIE_STUDIO_SUPERUSER_PASSWORD:-admin123}
      - AXIE_STUDIO_USERS=${AXIE_STUDIO_USERS:-}
      - NODE_ENV=production
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      langflow-backend:
        condition: service_healthy
    networks:
      - axie-studio-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: Reverse Proxy with SSL (Nginx)
  nginx-proxy:
    image: nginx:alpine
    container_name: axie-studio-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - axie-studio-frontend
    networks:
      - axie-studio-network
    profiles:
      - ssl

volumes:
  langflow_data:
    driver: local

networks:
  axie-studio-network:
    driver: bridge
